st = input()
st = st.replace("[","")
st = st.replace("]","")
st = st.replace("'","")
st = st.replace(",","")
st = st.replace(" ","")
st = st.replace("¬","n")
st = st.replace("∨","d")
st = st.replace("∧","c")
st = st.replace("⇒","i")
st = st.replace('⇔','e')
print(st)
